server:
  port: 8081
spring:
  session:
    store-type: redis
  security:
    user:
      name: user
      password: password
zuul:
  routes:
    hotels:
      path: /hotels
      serviceId: hotel-service
  sensitiveHeaders: Authorization, Set-Cookie
